#!/bin/bash
printf '\n%s\n' '==============================CLEAR memmory===================================='
sudo swapoff -a && swapon -a && printf '\n%s\n' '[#]	- Ram-cache and Swap Cleared'
sudo sh -c 'echo 1 >/proc/sys/vm/drop_caches' && printf '\n%s\n' '[1]	[#]	- stage clear done'
sudo sh -c 'echo 2 >/proc/sys/vm/drop_caches' && printf '\n%s\n' '[2]	[#]	- stage clear done'
sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' && printf '\n%s\n' '[3]	[#]	- stage clear done'
printf '\n%s\n' '====================================DONE======================================='
